FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./shared ./shared/
COPY ./tsconfig.json ./

COPY ./frontend/pnpm-lock.yaml ./frontend/
COPY ./frontend/package.json ./frontend/

WORKDIR /app/frontend
RUN pnpm install --frozen-lockfile

WORKDIR /app
COPY ./frontend ./frontend/

WORKDIR /app/frontend

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]


