services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      PORT: 3000
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore:
            - node_modules
        - path: ./shared
          action: sync
          target: /app/shared
          ignore:
            - node_modules
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/.env
          action: rebuild
        - path: ./frontend/dockerfile.dev
          action: rebuild
        - path: ./frontend/dockerfile
          action: rebuild
  gateway:
    build:
      context: .
      dockerfile: ./gateway/dockerfile.dev
    container_name: gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
    depends_on:
      - cms
      - auth
    develop:
      watch:
        - path: ./gateway
          action: sync
          target: /app/gateway
          ignore:
            - node_modules
        - path: ./shared
          action: sync
          target: /app/shared
          ignore:
            - node_modules
        - path: ./gateway/package.json
          action: rebuild
        - path: ./gateway/.env
          action: rebuild
        - path: ./gateway/dockerfile.dev
          action: rebuild
        - path: ./gateway/dockerfile
          action: rebuild
  auth:
    build:
      context: .
      dockerfile: ./auth/dockerfile.dev
    container_name: auth
    expose:
      - "4001"
    environment:
      NODE_ENV: production
      PORT: 4001
    develop:
      watch:
        - path: ./auth
          action: sync
          target: /app/auth
          ignore:
            - node_modules
        - path: ./shared
          action: sync
          target: /app/shared
          ignore:
            - node_modules
        - path: ./auth/package.json
          action: rebuild
        - path: ./auth/.env
          action: rebuild
        - path: ./auth/dockerfile.dev
          action: rebuild
        - path: ./auth/dockerfile
          action: rebuild
  cms:
    build:
      context: .
      dockerfile: ./cms-store/dockerfile.dev
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ai-store-delivery
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5433
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      HOST: 0.0.0.0
      PORT: 1337
    ports:
      - "1337:1337"
    volumes: 
      - ./cms-store:/app/cms-store/
      - /app/cms-store/node_modules
    depends_on:
      - db
    develop:
      watch:
        - path: ./cms-store
          action: sync
          target: /app/cms-store
          ignore:
            - node_modules
        - path: ./shared
          action: sync
          target: /app/shared
          ignore:
            - node_modules
        - path: ./cms-store/package.json
          action: rebuild
        - path: ./cms-store/.env
          action: rebuild
        - path: ./cms-store/dockerfile.dev
          action: rebuild
        - path: ./cms-store/dockerfile
          action: rebuild
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai-store-delivery
    expose:
      - "5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433
volumes:
  postgres_data:
