FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./shared ./shared/
COPY ./tsconfig.json ./

COPY ./gateway/pnpm-lock.yaml ./gateway/
COPY ./gateway/package.json ./gateway/

WORKDIR /app/gateway
RUN pnpm install --frozen-lockfile

WORKDIR /app
COPY ./gateway ./gateway/

WORKDIR /app/gateway

RUN pnpm build

EXPOSE 4000

CMD ["pnpm", "start:prod"]

