FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./shared ./shared/

COPY ./cms-store/pnpm-lock.yaml ./cms-store/
COPY ./cms-store/package.json ./cms-store/

WORKDIR /app/cms-store
RUN pnpm install --frozen-lockfile

WORKDIR /app
COPY ./cms-store ./cms-store/

WORKDIR /app/cms-store
RUN pnpm build

EXPOSE 1337

CMD ["pnpm", "start"]

