FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./shared ./shared/
COPY ./tsconfig.json ./

COPY ./auth/pnpm-lock.yaml ./auth/
COPY ./auth/package.json ./auth/

WORKDIR /app/auth
RUN pnpm install --frozen-lockfile

WORKDIR /app
COPY ./auth ./auth/

WORKDIR /app/auth

EXPOSE 4000

CMD ["pnpm", "start:dev"]

